version: "3.9"
services:
  db:
    image: postgres:16
    container_name: wegrow-postgres
    environment:
      POSTGRES_DB: wegrow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_wegrow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d wegrow"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata_wegrow:
