spring.datasource.url=jdbc:postgresql://localhost:5432/wegrowdb
spring.datasource.username=postgres
spring.datasource.password=password123

# Let Hibernate create/update tables from your JPA entities (simple and Flyway-free)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Server
server.port=8081


# JWT
jwt.secret=change-this-secret-please-0123456789
jwt.issuer=wegrow
jwt.expMinutes=120

